name: Windows Build (matrix)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      backend:
        description: "Optional single backend to run (WIN32_OPENGL or WIN32_DX11). Leave empty to run matrix."
        required: false
        default: ""
      mode:
        description: "Optional single mode to run (package or build). Leave empty to run both."
        required: false
        default: ""

concurrency:
  group: windows-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    # if user provided single backend/mode via workflow_dispatch, use those; otherwise use matrix
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(
          inputsMatrix(
            github.event.inputs.backend,
            github.event.inputs.mode
          )
        ) }}
    runs-on: windows-latest
    timeout-minutes: 120

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # single shallow fetch is usually fine for CI; increase if you need history
          fetch-depth: 1

      - name: Print job info
        shell: cmd
        run: |
          echo RUNNING: backend=%BACKEND% mode=%MODE%
        env:
          BACKEND: ${{ matrix.backend }}
          MODE: ${{ matrix.mode }}

      - name: Setup MSVC environment
        shell: cmd
        run: |
          REM Ensure we are using the provided setup script to configure cl/linker environment
          call code\custom\bin\setup_cl_x64.bat

      - name: Build or Package
        shell: cmd
        working-directory: 4cc\code
        run: |
          echo Building for backend: %BACKEND% mode: %MODE%
          if /I "%MODE%"=="package" (
            call bin\package.bat /D%BACKEND%
          ) else (
            call bin\build.bat /D%BACKEND%
          )
        env:
          BACKEND: ${{ matrix.backend }}
          MODE: ${{ matrix.mode }}

      - name: Collect build outputs (list)
        shell: cmd
        run: |
          echo "=== build dir listing ==="
          if exist build (
            dir /s build || echo "no build dir"
          ) else (
            echo "no build dir"
          )
          echo "=== distributions dir listing ==="
          if exist distributions (
            dir /s distributions || echo "no distributions dir"
          ) else (
            echo "no distributions dir"
          )
        working-directory: 4cc\code

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.backend }}-${{ matrix.mode }}
          path: |
            4cc/code/build/**
            4cc/code/distributions/**
