name: Build 4cc

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      backend:
        description: 'Graphics backend to use'
        required: false
        default: 'WIN32_OPENGL'
        type: choice
        options:
          - WIN32_OPENGL
          - WIN32_DX11

jobs:
  build-windows:
    runs-on: windows-latest
    
    strategy:
      matrix:
        backend: ${{ github.event.inputs.backend && fromJSON(format('["{0}"]', github.event.inputs.backend)) || fromJSON('["WIN32_OPENGL", "WIN32_DX11"]') }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup MSVC Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
      
      - name: Verify MSVC setup
        shell: cmd
        run: |
          where cl
          cl
      
      - name: Build distribution package
        shell: cmd
        working-directory: code
        run: |
          call bin\package.bat /D${{ matrix.backend }}
      
      - name: Verify distribution was created
        shell: pwsh
        run: |
          if (!(Test-Path "distributions")) {
            Write-Error "Distributions directory not found!"
            exit 1
          }
          Get-ChildItem distributions -Recurse
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 4cc-windows-${{ matrix.backend }}
          path: distributions/
          if-no-files-found: error
          retention-days: 30
