name: Build 4cc

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      backend:
        description: 'Graphics backend to use'
        required: false
        default: 'WIN32_OPENGL'
        type: choice
        options:
          - WIN32_OPENGL
          - WIN32_DX11

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup MSVC
        uses: microsoft/setup-msbuild@v2
      
      - name: Setup MSVC toolchain
        shell: cmd
        run: |
          cd code\custom\bin
          call setup_cl_x64.bat
      
      - name: Build distribution
        shell: cmd
        working-directory: code
        run: |
          if "${{ github.event.inputs.backend }}" == "WIN32_DX11" (
            call bin\package.bat /DWIN32_DX11
          ) else (
            call bin\package.bat /DWIN32_OPENGL
          )
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 4cc-windows-${{ github.event.inputs.backend || 'WIN32_OPENGL' }}
          path: distributions/*
          if-no-files-found: error
          retention-days: 30
