name: Windows Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      backend:
        description: "Graphics backend (WIN32_OPENGL or WIN32_DX11)"
        required: false
        default: "WIN32_OPENGL"
      mode:
        description: "Build type (package or build)"
        required: false
        default: "package"

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        backend: [ "WIN32_OPENGL", "WIN32_DX11" ]
        mode: [ "package", "build" ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSVC environment
        shell: cmd
        run: |
          echo Setting up MSVC environment...
          call code\custom\bin\setup_cl_x64.bat

      - name: Build project
        shell: cmd
        working-directory: 4cc\code
        run: |
          echo Building project using %mode% mode with backend %backend%
          if "%mode%"=="package" (
            call bin\package.bat /D%backend%
          ) else (
            call bin\build.bat /D%backend%
          )
        env:
          backend: ${{ matrix.backend }}
          mode: ${{ matrix.mode }}

      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.backend }}-${{ matrix.mode }}-artifacts
          path: |
            4cc/code/build/**
            4cc/code/distributions/**
